---
exclude: '^$'
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
        name: "Executable text files have shebangs"
      - id: trailing-whitespace
        types: [xml]
      - id: trailing-whitespace
        types: [yaml]
      - id: trailing-whitespace
        types: [markdown]
      - id: check-yaml
        args:
          - "-m"

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.19.0
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.6.0"
    hooks:
      - id: markdownlint
        types: [markdown]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: "1.11.2"
    hooks:
      - id: script-must-have-extension
      - id: shellcheck
        name: shellcheck(linter)
        types: [shell]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook.git
    rev: v2.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

#  - repo: https://github.com/dkolepp/pylint
#    rev: master
#    hooks:
#      - id: pylint
#        args:
#          - "--error-threshold=8.0"
